spring.application.name=examen


#connection info
api.url.domain = https://api.tvmaze.com

#database info
mongo.db.uri=mongodb+srv://charlychav410_db_user:HUhATP75LeURrBLl@clusterprueba.vvhdtht.mongodb.net